### ISSUE TITLE
Не засчитывается вопрос, подразумевающий выбор одного ответа в вопросе в модуле CSS Basic

### ISSUE THREAD

**Issue by Schekhovtsov** [it-incubator/interview-questions-db#30]
Не засчитывается вопрос, подразумевающий выбор одного ответа. Утверждается, что ответ не полный.

![Screenshot_2023-03-04-15-48-53-659_ru yandex searchplugin](https://user-images.githubusercontent.com/3204270/222902739-949f277f-9f69-422e-8d94-aa117aa9a21f.jpg)

**Comment by Schekhovtsov** [comment]
Аналогичная проблема в модуле JS Basic

![Screenshot_2023-03-04-20-05-40-077_ru yandex searchplugin](https://user-images.githubusercontent.com/3204270/222919223-850ebe55-89cf-48dd-9d8e-7687d36c93f7.jpg)

**Comment by StarkovSergey** [comment]
Огромное спасибо! Исправлено :)
