### ISSUE TITLE
JS Basic: Что вернёт выражение hobbits.pop()?

### ISSUE THREAD

**Issue by EvgenyTomson** [it-incubator/interview-questions-db#33]
![JS_Basics_pop](https://user-images.githubusercontent.com/104619230/223389161-fd5ab64d-fa2a-4954-b49a-2a9a8e790d2f.jpg)

**Comment by StarkovSergey** [comment]
Да, в коде должно быть `const hobbits`, тогда правильный ответ `Pippin`. Скоро поправим! Спасибо)
