### ISSUE TITLE
Привет, вопрос по тесту JS Basic (Преобразование типов)

### ISSUE THREAD

**Issue by onlypositivemind** [it-incubator/interview-questions-db#35]
![image](https://user-images.githubusercontent.com/109303573/223689662-b79f4f04-944b-4183-ad61-d07e154a67e3.png)

В книге 'JavaScript полное руководство 7-е издание' план преобразования описан таким образом:
![image](https://user-images.githubusercontent.com/109303573/223690697-927a5686-0030-4821-9f81-f545be31b2c4.png)

**Comment by StarkovSergey** [comment]
Да, у Флэнагана даётся немного другой алгоритм преобразования, хотя результат всё-равно такой же. На learn.js объяснение даётся ещё проще: при сравнении оператором `==`, операнды преобразуются к числам (если это не `null` и `undefined`). Мне кажется, что так, действительно, проще запомнить работу нестрого сравнения - хотя, возможно, язык внутри работает по более сложному алгоритму
